# Generated by Django 3.1.1 on 2020-10-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0003_auto_20201030_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='userid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
