# Generated by Django 3.1.1 on 2020-11-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0003_loginstats_logout_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginstats',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loginstats',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loginstats',
            name='org',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loginstats',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loginstats',
            name='timezone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='timezone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
