# Generated by Django 3.1.1 on 2020-11-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0004_auto_20201103_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='org',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
